### ISSUE TITLE
Consider adding 'another' way to specify visibility

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/easy-ext#13]
The current way is not convenient when there are many associated items. Also, empty traits cannot be public.

Related: #8

**Comment by taiki-e** [comment]
Maybe it should be an attribute argument like `vis = pub`?

**Comment by taiki-e** [comment]
FYI: This is how to specify visibility in current easy-ext: https://docs.rs/easy-ext/0.2.0/easy_ext/attr.ext.html#visibility

(As in the [readme example](https://github.com/taiki-e/easy-ext#examples), if the method is `pub` then the trait will also be `pub`)

**Comment by Boscop** [comment]
@taiki-e Can you please allow it by accepting `pub` as first arg, like the `extend` crate? :)
https://docs.rs/extend/0.3.0/extend/#configuration

**Comment by taiki-e** [comment]
I can look at this next week.

**Comment by taiki-e** [comment]
Filed #25

**Comment by taiki-e** [comment]
Published in 0.2.6.
