### ISSUE TITLE
Remove dependency on syn & quote

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/easy-ext#28]
Pretty much the same request as taiki-e/const_fn#16. The standback crate consists solely of extension traits (literally), but is meant to compile at very little cost. I'd like to use this crate as a dependency, but the weight of syn & quote (specifically syn as mentioned in the linked issue) is a deal-breaker.

If this could be removed, it would be great. If not, no big deal — I'll probably write some hacky proc macro (or maybe even macro_rules if I can manage).

**Comment by taiki-e** [comment]
#30 implements what I considered to be the most difficult part of this issue, the handling (parsing) of generics and types.

(...And when I was writing tests for compatibility with some unstable syntax like specialization, I noticed that `pub impl` is syntactically accepted by rustc (#31).)

**Comment by taiki-e** [comment]
Released in [v0.2.8](https://github.com/taiki-e/easy-ext/releases/tag/v0.2.8).
