### ISSUE TITLE
error: expected `{`

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/easy-ext#36]
Not entirely sure where this is originating from, but it appears to be a bug given that the syntax is otherwise valid. At first I thought it was because the comma was required (which would be odd but acceptable), but CI is failing even with it.

Check out the [build failure](https://github.com/jhpratt/standback/runs/2976722048?check_suite_focus=true) on @jhpratt/standback for an example. This error occurs in a number of places.

**Comment by taiki-e** [comment]
Published 0.2.9 which fixes this issue. Thanks for the reporting!

**Comment by jhpratt** [comment]
Thank you for the very fast bugfixes as always!
