### ISSUE TITLE
Add motivation or use case for use of just `#[ext]`

### ISSUE THREAD

**Issue by ronanM** [taiki-e/easy-ext#44]
Could you please complete the documentation with the motivation or a use case for this?

> Note that in this case, #[ext] assigns a random name, so you cannot import/export the generated trait.

**Comment by taiki-e** [comment]
There is no need to explicitly reference the name of the extended trait when using it in the current module or importing with a glob import.

**Comment by ronanM** [comment]
:+1:  maybe your explanation could be added to the doc.
