### ISSUE TITLE
How to derive the extension trait from other trait?

### ISSUE THREAD

**Issue by Boscop** [taiki-e/easy-ext#8]
How to derive the extension trait from other trait, is it supported? 
If not, it would be very useful to add..

**Comment by taiki-e** [comment]
It can be written as:
https://github.com/taiki-e/easy-ext/blob/d8b9a942545f5605b6ad488c6887e34d81c75496/tests/test.rs#L48-L53

**Comment by Boscop** [comment]
@taiki-e But this will generate `impl<I: IntoIterator> IterExt for I {`, right?
I would like to express `trait GeneratedTrait: SuperTrait { ..`. I often need this with e.g. `Default` etc.
This is orthogonal to the `<I: Trait>` bound. Ideally, both should be possible together..

**Comment by taiki-e** [comment]
@Boscop Sorry for the late reply!

IIUC, `where Self: Trait` behaves like super-trait `: Trait`: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=31dfc763b1f0d578472188287c83cab9)

```rust
pub trait A where
    Self: Default,
{
    fn b(&self) {}
}
impl A for () {}

pub fn c<T: A>() -> T {
    T::default()
}
```

So, you could write as follows:

```rust
#[easy_ext::ext(A)]
impl<T> T
where
    Self: Default,
{
    fn b(&self) {}
}
```

**Comment by Boscop** [comment]
@taiki-e Ok, and how to make the trait `pub`? :)

**Comment by taiki-e** [comment]
> how to make the trait `pub`? :)

Just make the all methods `pub`.

```rust
#[easy_ext::ext(A)]
impl<T> T
{
    pub fn b(&self) {} 
//  ^^^
}
```

https://docs.rs/easy-ext/0.1.7/easy_ext/attr.ext.html#visibility

**Comment by taiki-e** [comment]
Also, once #15 merged, the following code's `<I: IntoIterator>` will be converted to `where Self: IntoIterator`.

```rust
#[ext(IterExt)] 
 impl<I: IntoIterator> I { 
     fn _next(self) -> Option<I::Item> { 
         self.into_iter().next() 
     } 
 } 
```

generated:
```rust
trait IterExt 
where Self: IntoIterator 
{ 
     fn _next(self) -> Option<Self::Item>;
}
impl<I: IntoIterator> IterExt for I { 
     fn _next(self) -> Option<I::Item> { 
         self.into_iter().next() 
     } 
 } 
```
